resource "local_file" "sshkey" {
  filename = local.sshkey_file
}

resource "local_file" "sshkey_public" {
  filename = "${local.sshkey_file}.pub"
}

resource "null_resource" "ssh-keygen" {
  provisioner "local-exec" {
    command = "ssh-keygen -t ${var.sshkey_config.algorithm} -b ${var.sshkey_config.bits} -C ${var.tags.name} -f ${local.sshkey_file} -q -N '' -m pem <<< y;chmod 400 ${local.sshkey_file}"
  }
  depends_on = [
    resource.local_file.sshkey
  ]
}

data "local_file" "sshkey_private" {
  filename = local.sshkey_file
  depends_on = [
    null_resource.ssh-keygen
  ]
}

data "local_file" "sshkey_public" {
  filename = "${local.sshkey_file}.pub"
  depends_on = [
    null_resource.ssh-keygen
  ]
}

resource "aws_secretsmanager_secret" "sshkey_secret" {
  name                    = "${var.tags.name}_sshkey"
  description             = "${var.tags.name} SSH key generated by Terraform"
  recovery_window_in_days = local.secretsmanager_config.recovery_window_in_days
  tags                    = var.tags
}

resource "aws_secretsmanager_secret_version" "sshkey_value" {
  secret_id     = aws_secretsmanager_secret.sshkey_secret.id
  secret_string = data.local_file.sshkey_private.content
  depends_on = [
    null_resource.ssh-keygen
  ]
}

resource "aws_key_pair" "sshkey" {
  key_name   = var.tags.name
  public_key = data.local_file.sshkey_public.content
}

/*
  Below block destroys local ssh key files when infrastructure is destroyed.
*/
resource "null_resource" "ssh-keygen-delete" {
  triggers = {
    filename     = "${local.sshkey_file}"
    filename_pub = "${local.sshkey_file}.pub"
  }
  # count = local.sshkey_config.destroy_local_ssh_files ? 1 : 0
  provisioner "local-exec" {
    command = "rm -f ${self.triggers.filename};rm -f ${self.triggers.filename_pub};"
    when    = destroy
  }
  depends_on = [
    aws_secretsmanager_secret_version.sshkey_value,
    aws_key_pair.sshkey
  ]
}








